---
- name: Establish home directory.
  set_fact:
    omz_user_home_dir: "{{ (ansible_system == 'Darwin') | ternary('Users', 'home') }}"

- name: Ensure zsh is installed on linux
  package:
    name: "zsh"
    state: present
  when:
    - "ansible_system == 'Linux'"
    - "omz_install_zsh"
    # zsh is the default shell on MacOS anyway, so we don't need to install it first

- name: Get zsh installed path.
  shell: "command -v zsh"
  register: omz_zsh_installed_path
  changed_when: false

- name: Set user shell to zsh.
  user:
    name: "{{ omz_user.name }}"
    shell: "{{ omz_zsh_installed_path.stdout }}"
